import * as constant from './constants.js';

export const cities = [{
  type: constant.Type.TAXI,
  id: `Airport`,
  title: `Taxi to`,
  icon: constant.Icon[constant.Type.TAXI],
  offers: constant.OFFERS[constant.Type.TAXI],
  description: constant.getRandomParam(constant.DESCRIPTION, constant.DESCRIPTIONS_COUNT, `.`),
  picture: constant.getRandomPicture(),
  timeStart: constant.getRandomParam(constant.TIME_START, constant.TIME_COUNT).join(``),
  timeEnd: constant.getRandomParam(constant.TIME_END, constant.TIME_COUNT).join(``),
  price: constant.PRICE[constant.Type.TAXI],
  currencyRate: constant.CURRENCY_RATE,
},
{
  type: constant.Type.FLIGHT,
  id: `Geneva`,
  title: `Flight to`,
  icon: constant.Icon[constant.Type.FLIGHT],
  offers: constant.OFFERS[constant.Type.FLIGHT],
  description: constant.getRandomParam(constant.DESCRIPTION, constant.DESCRIPTIONS_COUNT, `.`),
  picture: constant.getRandomPicture(),
  timeStart: constant.getRandomParam(constant.TIME_START, constant.TIME_COUNT).join(``),
  timeEnd: constant.getRandomParam(constant.TIME_END, constant.TIME_COUNT).join(``),
  price: constant.PRICE[constant.Type.FLIGHT],
  currencyRate: constant.CURRENCY_RATE,
},
{
  type: constant.Type.DRIVE,
  id: `Chamonix`,
  title: `Drive to`,
  icon: constant.Icon[constant.Type.DRIVE],
  offers: constant.OFFERS[constant.Type.DRIVE],
  description: constant.getRandomParam(constant.DESCRIPTION, constant.DESCRIPTIONS_COUNT, `.`),
  picture: constant.getRandomPicture(),
  timeStart: constant.getRandomParam(constant.TIME_START, constant.TIME_COUNT).join(``),
  timeEnd: constant.getRandomParam(constant.TIME_END, constant.TIME_COUNT).join(``),
  price: constant.PRICE[constant.Type.DRIVE],
  currencyRate: constant.CURRENCY_RATE,
},
{
  type: constant.Type.CHECK,
  id: `hotel`,
  title: `Check into a`,
  icon: constant.Icon[constant.Type.CHECK],
  offers: constant.OFFERS[constant.Type.CHECK],
  description: constant.getRandomParam(constant.DESCRIPTION, constant.DESCRIPTIONS_COUNT, `.`),
  picture: constant.getRandomPicture(),
  timeStart: constant.getRandomParam(constant.TIME_START, constant.TIME_COUNT).join(``),
  timeEnd: constant.getRandomParam(constant.TIME_END, constant.TIME_COUNT).join(``),
  price: constant.PRICE[constant.Type.CHECK],
  currencyRate: constant.CURRENCY_RATE,
},
];
