import * as constant from './constants.js';

export const cities = [{
  type: constant.TYPES.TAXI,
  id: `Airport`,
  title: `Taxi to`,
  icon: constant.ICONS[constant.TYPES.TAXI],
  offers: constant.OFFERS[constant.TYPES.TAXI],
  description: constant.getRandomParam(constant.DESCRIPTION, constant.DESCRIPTIONS_COUNT, `.`),
  picture: constant.getRandomPicture(),
  timeStart: constant.getRandomParam(constant.TIME_START, constant.TIME_COUNT).join(``),
  timeEnd: constant.getRandomParam(constant.TIME_END, constant.TIME_COUNT).join(``),
  price: constant.PRICE[constant.TYPES.TAXI],
  currencyRate: constant.CURRENCY_RATE,
},
{
  type: constant.TYPES.FLIGHT,
  id: `Geneva`,
  title: `Flight to`,
  icon: constant.ICONS[constant.TYPES.FLIGHT],
  offers: constant.OFFERS[constant.TYPES.FLIGHT],
  description: constant.getRandomParam(constant.DESCRIPTION, constant.DESCRIPTIONS_COUNT, `.`),
  picture: constant.getRandomPicture(),
  timeStart: constant.getRandomParam(constant.TIME_START, constant.TIME_COUNT).join(``),
  timeEnd: constant.getRandomParam(constant.TIME_END, constant.TIME_COUNT).join(``),
  price: constant.PRICE[constant.TYPES.FLIGHT],
  currencyRate: constant.CURRENCY_RATE,
},
{
  type: constant.TYPES.DRIVE,
  id: `Chamonix`,
  title: `Drive to`,
  icon: constant.ICONS[constant.TYPES.DRIVE],
  offers: constant.OFFERS[constant.TYPES.DRIVE],
  description: constant.getRandomParam(constant.DESCRIPTION, constant.DESCRIPTIONS_COUNT, `.`),
  picture: constant.getRandomPicture(),
  timeStart: constant.getRandomParam(constant.TIME_START, constant.TIME_COUNT).join(``),
  timeEnd: constant.getRandomParam(constant.TIME_END, constant.TIME_COUNT).join(``),
  price: constant.PRICE[constant.TYPES.DRIVE],
  currencyRate: constant.CURRENCY_RATE,
},
{
  type: constant.TYPES.CHECK,
  id: `hotel`,
  title: `Check into a`,
  icon: constant.ICONS[constant.TYPES.CHECK],
  offers: constant.OFFERS[constant.TYPES.CHECK],
  description: constant.getRandomParam(constant.DESCRIPTION, constant.DESCRIPTIONS_COUNT, `.`),
  picture: constant.getRandomPicture(),
  timeStart: constant.getRandomParam(constant.TIME_START, constant.TIME_COUNT).join(``),
  timeEnd: constant.getRandomParam(constant.TIME_END, constant.TIME_COUNT).join(``),
  price: constant.PRICE[constant.TYPES.CHECK],
  currencyRate: constant.CURRENCY_RATE,
},
];
